"""Driving the Compose stack, and the repository addon that generates the indexer's prefix map."""

import hashlib
import json
import subprocess
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "generated"
SNAPSHOTS = ROOT / "snapshots"
ADDONS = GENERATED / "addons"

INDEXER_SERVICE = "batch-indexer"
CORE_SERVICES = ["postgres", "transform-core-aio", "alfresco", "opensearch"]

# The namespace prefix map is generated by the repository, through this addon. Pinned by version
# and checksum, downloaded at run time, and mounted into the repository by compose.yaml. Nothing
# is vendored here.
ADDON_VERSION = "1.2.0"
ADDON_SHA256 = "3d4a3e34397ee7af8f9f097a0c7539744050e59edafb89db66ad6cc0f5fceede"
ADDON_URL = (
    "https://github.com/AlfrescoLabs/model-ns-prefix-mapping/releases/download/"
    "%s/model-ns-prefix-mapping-%s.jar" % (ADDON_VERSION, ADDON_VERSION)
)
ADDON_JAR = ADDONS / "model-ns-prefix-mapping.jar"


def env():
    """The pinned tags and credentials from .env."""
    values = {}
    for line in (ROOT / ".env").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


# --- Compose ---


def compose(*args, capture=False, check=True):
    command = ["docker", "compose", *args]
    if capture:
        result = subprocess.run(
            command, cwd=ROOT, check=check, capture_output=True, text=True
        )
        return result.stdout
    subprocess.run(command, cwd=ROOT, check=check)
    return None


def up_core():
    ensure_addon()
    compose("up", "-d", *CORE_SERVICES)


def up_indexer():
    compose("--profile", "indexer", "up", "-d", INDEXER_SERVICE)


def restart_indexer():
    """Recreate the indexer so it re-reads the mounted prefix map."""
    compose("--profile", "indexer", "rm", "-sf", INDEXER_SERVICE)
    up_indexer()


def down():
    compose("--profile", "indexer", "down", "-v")


def running_services():
    """Compose has emitted both a JSON array and one object per line over its versions."""
    output = (compose("ps", "--all", "--format", "json", capture=True) or "").strip()
    if not output:
        return []
    try:
        parsed = json.loads(output)
        return parsed if isinstance(parsed, list) else [parsed]
    except json.JSONDecodeError:
        return [json.loads(line) for line in output.splitlines() if line.strip()]


def indexer_container_exists():
    return any(item.get("Service") == INDEXER_SERVICE for item in running_services())


def logs(service=INDEXER_SERVICE, tail="all"):
    return compose("logs", "--no-log-prefix", "--tail", str(tail), service, capture=True) or ""


# --- The indexer's namespace prefix map ---


def ensure_addon():
    """Download the prefix-map addon into generated/addons, once, and verify its checksum.

    compose.yaml mounts it into the repository webapp, so it has to be on disk before the
    repository container starts.
    """
    if ADDON_JAR.exists() and _sha256(ADDON_JAR) == ADDON_SHA256:
        return ADDON_JAR

    ADDONS.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(ADDON_URL, timeout=120) as response:
        content = response.read()
    digest = hashlib.sha256(content).hexdigest()
    if digest != ADDON_SHA256:
        raise RuntimeError(
            "%s has checksum %s, expected %s" % (ADDON_URL, digest, ADDON_SHA256)
        )
    ADDON_JAR.write_bytes(content)
    return ADDON_JAR


def _sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_prefixes(prefix_uri_map):
    """Write the map the container reads at generated/prefixes.json."""
    GENERATED.mkdir(exist_ok=True)
    target = GENERATED / "prefixes.json"
    target.write_text(
        json.dumps({"prefixUriMap": dict(prefix_uri_map)}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return target
